sudo: required
services:
  - docker

before_install:
  - docker build -t mack031892/react-test -f ./client/Dockerfile.dev ./client
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh

script:
  - docker run mack031892/react-test npm test

after_success:
  - docker build -t mack031892/multi-client ./client
  - docker build -t mack031892/multi-server ./server
  - docker build -t mack031892/multi-nginx ./nginx
  - docker build -t mack031892/multi-worker ./worker
  # login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images to push them to docker-hub
  - docker push mack031892/multi-client
  - docker push mack031892/multi-server
  - docker push mack031892/multi-nginx
  - docker push mack031892/multi-worker

  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
  - docker tag mack031892/multi-client registry.heroku.com/$HEROKU_APP/web

deploy:
  provider: script
  script: docker push registry.heroku.com/$HEROKU_APP/web;
    heroku container:release web --app $HEROKU_APP
  on:
    branch: main
